CC = gcc -ggdb
CFLAGS = -std=gnu11 -Wall -Wextra
LDFLAGS = -pthread
all: zad1 zad2 zad3 zad4

zad1: zad1.o
zad2: zad2.o
zad3: zad3.o
zad4: zad4.o

clean:
	rm -f zad1 zad2 zad3 zad4
	rm -f *.o
	rm -f *~


